-- TODO: create application role CRM_APP with LOGIN and limited grants (no SUPERUSER)
-- Example shape (adjust for your shared vs local policy):
-- CREATE ROLE crm_app LOGIN PASSWORD 'use-env-not-git';
-- GRANT CONNECT ON DATABASE crm TO crm_app;


CREATE ROLE crm_app LOGIN PASSWORD 'use-env-not-git';

GRANT CONNECT ON DATABASE crm TO crm_app;


-- Let crm_app use the public schema (CONNECT alone doesn't grant this)
GRANT USAGE ON SCHEMA public TO crm_app;

-- Grant DML on existing tables (not DDL — no CREATE/DROP/ALTER)
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO crm_app;

-- So it can use identity/sequence-backed columns (BIGINT GENERATED BY DEFAULT AS IDENTITY)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO crm_app;

-- So future tables created by the schema owner also get these grants automatically
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO crm_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO crm_app;